### ISSUE TITLE
Documentation: Difference between this and "regular" SVD

### ISSUE THREAD

**Issue by BradKML** [gbolmier/funk-svd#7]
As Wikipedia had suggested, Funk et. al. is not using the regular form of SVD with three variable, but rather a modified form of NMF with two variables but faster convergence and speed.

With reference to the Funk:
- https://www.wikiwand.com/en/Matrix_factorization_(recommender_systems)#/Funk_MF

With reference to SVD:
- https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.TruncatedSVD.html
- https://numpy.org/doc/stable/reference/generated/numpy.linalg.svd.html

Would it be good to explain how the optimization differs from NMF?

**Comment by gbolmier** [comment]
Hi @BrandonKMLee, Thank you for taking the time to drop a comment 😃 

So far the `README.md` is the only documentation of the project. I would prefer to keep it short, concise, and not go too far into the theoretical details. The important part of the optimization process is already covered and a software documentation isn't supposed to explain much about the mathematical part. Nevertheless, I think it makes sense to add references for people interested in more background; I'll clean up the `README.md` and add some in the next days 👍

**Comment by BrandonKMLee** [comment]
Yeah, there are discrepancies between this repo and https://towardsdatascience.com/beginners-guide-to-creating-an-svd-recommender-system-1fd7326d1f65 on the way they handle null values.

**Comment by BradKML** [comment]
I think I might have asked the same question in an SVD repo that is slightly more relevant. https://github.com/ZWMiller/svdRec/issues/1

**Comment by gbolmier** [comment]
Added a **References** section in `README.md` (cf. corresponding [commit](https://github.com/gbolmier/funk-svd/commit/3333ca74170a1803db8de2e58d83a0cb6b161c7e))
