### ISSUE TITLE
Documentation: Dataset shape requirements

### ISSUE THREAD

**Issue by BradKML** [gbolmier/funk-svd#8]
For SVD to be usable in other settings, it would be useful to describe the acceptable datatype for SVD.

1. **accepted inputs**: From reading this as part of the MovieLens dataset we can safely assume that it follows the user-item-ratings format, while the testing tool uses the user-item format. These format specifications should be well documented for alternative usage (due to dataframe columns having the possible issue of misordering).
2. **expanding dataset**: Since the ID hash table is done within the SVD object, every time the data expands, the SVD object would also have to be rebuilt from scratch instead of expanding `_preprocess_data` fields accordingly.
3. **re-fitting**: If there are data that is given for updating, the SVD latent factor matrices, and bias matrices should be updated from the new data. However, whether the updating procedures should include times 1 to X-1 or not in time step X, is not documented.
4. **caching to external object**: Since sometimes the SVD has to go offline, caching the object is necessary. It would be useful to know if it is better to store the data in CSVs (for readability) or Pickle/DataTables (for legibility).
5. **Explanation of feature**: It should be noted that, unlike other base repos that utilize dense or sparse matrices, this repo is more akin to machine learning, and that it does not "update by the table" but rather "update by the entry". Also an explanation of validation/test dataset is needed (especially in a practical non-evaluation setting). https://www.wikiwand.com/en/Training,_validation,_and_test_sets

**Comment by gbolmier** [comment]
1. This is documented in the `SVD` class [docstring](https://github.com/gbolmier/funk-svd/blob/3333ca74170a1803db8de2e58d83a0cb6b161c7e/funk_svd/svd.py#L75-L91)
2. Unfortunately the model doesn't learn incrementally so far (updating a pretrained model with new ratings), therefore the mapping has to be done every time we call the `fit` method
3. Referring to the previous point that would definitely be nice to have. Until then, it might be interesting to have a look at what has been implemented in the `river` package (see [`river.reco.FunkMF`](https://riverml.xyz/dev/api/reco/FunkMF/))
4. I think it's up to the user and the use case
5. This software is only a tool and therefore should document its usage, not the maths behind the algorithm implemented, it's the user's responsibility to study it (see answer in #7 and the newly [References](https://github.com/gbolmier/funk-svd#references) section added)
